const colors = ['#ff6b6b','#ff9f43','#ffd166','#2ecc71','#24c4c8','#4d96ff','#7b6cf6','#c06cdb','#f278b5','#ec568e'];
const grid = document.querySelector('#grid'), timer = document.querySelector('#timer'), matchedText = document.querySelector('#matched'), movesText = document.querySelector('#moves'), status = document.querySelector('#status'), result = document.querySelector('#result');
let first = null, lock = false, matched = 0, moves = 0, seconds = 30, tick = null;
const shuffle = list => [...list].sort(() => Math.random() - .5);
function formatTime(value){return `0:${String(Math.max(0,value)).padStart(2,'0')}`}
function start(){clearInterval(tick);first=null;lock=false;matched=0;moves=0;seconds=30;result.classList.remove('show');result.setAttribute('aria-hidden','true');matchedText.textContent='0';movesText.textContent='0';timer.textContent=formatTime(seconds);status.textContent='접힌 검은 우산을 탭해 색을 확인하고, 같은 두 개를 찾아 고정하세요.';render();tick=setInterval(()=>{seconds--;timer.textContent=formatTime(seconds);if(seconds<=0){clearInterval(tick);finish(false)}},1000)}
function render(){grid.innerHTML='';shuffle([...colors,...colors]).forEach((color,index)=>{const button=document.createElement('button');button.className='umbrella';button.type='button';button.dataset.color=color;button.setAttribute('aria-label','접힌 우산');button.innerHTML=`<span class="umbrella-inner"><span class="closed"></span><span class="open"><span class="canopy" style="--c:${color}"></span></span></span>`;button.addEventListener('click',()=>choose(button));grid.append(button)})}
function choose(card){if(lock||card.classList.contains('is-open')||card.classList.contains('matched'))return;card.classList.add('is-open');card.setAttribute('aria-label','펼친 우산');if(!first){first=card;return}moves++;movesText.textContent=moves;if(first.dataset.color===card.dataset.color){first.classList.add('matched');card.classList.add('matched');matched++;matchedText.textContent=matched;status.textContent='같은 컬러를 찾았어요! 이 우산은 고정됩니다.';first=null;if(matched===10)finish(true)}else{lock=true;status.textContent='다른 컬러예요. 잠시 후 다시 접힙니다.';setTimeout(()=>{first.classList.remove('is-open');card.classList.remove('is-open');first=null;lock=false;status.textContent='다시 두 개의 우산을 골라보세요.'},650)}}
function finish(success){lock=true;clearInterval(tick);if(success){result.classList.add('show');result.setAttribute('aria-hidden','false')}else{status.textContent='시간이 끝났어요. 다시 도전해 보세요!'}}
document.querySelector('#restart').addEventListener('click',start);document.querySelector('#play-again').addEventListener('click',start);start();
